//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cw2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionInstance
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Transaction_Id { get; set; }
    }
}
